import logging
import copy
from cardio import session, Card, Deck, handlers
from cardio.agent_strategies import Turn0OnlyStrategy, GridPos, SimpleHumanStrategy
from cardio.card_blueprints import create_cards_from_blueprints

# QQ: Could we use a special view that generates output that makes testing much easier?

# FIXME Use sublist here: https://stackoverflow.com/questions/23667731/determine-if-all-elements-in-a-list-are-present-and-in-the-same-order-in-another



def test_simple_initial_setup(caplog):
    caplog.set_level(logging.DEBUG)
    session.setup()
    session.view.non_blocking = True

    cs = Turn0OnlyStrategy(
        [
            (GridPos(0, 1), Card(name="Steed", initial_power=2, initial_health=10)),
            (GridPos(1, 0), Card(name="Dog", initial_power=2, initial_health=5)),
            (GridPos(2, 0), Card(name="Cat", initial_power=1, initial_health=3)),
        ]
    )
    handlers.handle_fight(computerstrategy=cs)

    targetgrid = [[None for _ in range(4)] for _ in range(3)]
    targetgrid[1][0] = Card(
        name="Dog", initial_power=2, initial_health=5, power=2, health=3
    )
    targetgrid[1][1] = Card(
        name="Steed", initial_power=2, initial_health=10, power=2, health=10
    )
    assert [[c for c in session.grid[linei]] for linei in range(3)] == targetgrid

    for logentry in [
        "Cat becomes active",
        "Cat attacks Dog",
        "Dog gets attacked by Cat",
        "Dog new health: 4",
        "Dog becomes active",
        "Dog attacks Cat",
        "Cat gets attacked by Dog",
        "Cat new health: 1",
        "Preparing Steed, moving to computer line",
        "Steed becomes active",
        "Player Schnuzgi loses 2 health, new health 3",
        "Cat becomes active",
        "Cat attacks Dog",
        "Dog gets attacked by Cat",
        "Dog new health: 3",
        "Dog becomes active",
        "Dog attacks Cat",
        "Cat gets attacked by Dog",
        "Cat dies.",
        "Removed card from [2, 0]",
        "Steed becomes active",
        "Player Schnuzgi loses 2 health, new health 1",
        "Dog becomes active",
        "Player Schnuzgi loses 2 health, new health -1",
        "Steed becomes active",
        "Player Schnuzgi loses 2 health, new health -3",
        "Player Schnuzgi loses 1 life, 0 life/lives left, 3 overflow damage",
    ]:
        assert logentry in caplog.text


def test_human_decks_managed_correctly(caplog, mocker):
    caplog.set_level(logging.DEBUG)
    session.setup()

    original_cards = create_cards_from_blueprints(
        ["Koala", "Weasel", "Lynx", "Porcupine"]
    )
    session.humanagent.deck = Deck(copy.deepcopy(original_cards))

    session.view.non_blocking = True
    mocker.patch("cardio.session.view")  # Deactivate the view to improve performance

    session.humanagent.health = 100
    cs = Turn0OnlyStrategy(
        [
            (GridPos(1, 0), Card(name="Hulk", initial_power=2, initial_health=100)),
            (GridPos(1, 1), Card(name="Hulk", initial_power=2, initial_health=100)),
            (GridPos(1, 2), Card(name="Hulk", initial_power=2, initial_health=100)),
            (GridPos(1, 3), Card(name="Hulk", initial_power=2, initial_health=100)),
        ]
    )
    mocker.patch("cardio.deck.Deck.shuffle")

    hs = SimpleHumanStrategy(session.grid)
    handlers.handle_fight(computerstrategy=cs, humanstrategy=hs)

    assert len(session.humanagent.deck.cards) == len(original_cards)
    # FIXME Compare cards more deeply

    for logentry in [
        "Handdeck size: 4 (Koala,Weasel,Lynx,Hamster)",
        "Fightdeck size: 1 (Porcupine)",
        "Hamsterdeck size: 9 (Hamster,Hamster,Hamster,Hamster,Hamster,Hamster,Hamster,Hamster,Hamster)",
        "Useddeck size: 0 ()",
        "Human draws Hamster",
        "Human plays Koala on GridPos(line=2, slot=0)",
        "Handdeck size: 4 (Weasel,Lynx,Hamster,Hamster)",
        "Fightdeck size: 1 (Porcupine)",
        "Hamsterdeck size: 8 (Hamster,Hamster,Hamster,Hamster,Hamster,Hamster,Hamster,Hamster)",
        "Useddeck size: 1 (Koala)",
        "Koala becomes active",
        "Koala attacks Hulk",
        "Hulk gets attacked by Koala",
        "Hulk new health: 99",
        "Hulk becomes active",
        "Hulk attacks Koala",
        "Koala gets attacked by Hulk",
        "Koala new health: 1",
        "Hulk becomes active",
        "Player Schnuzgi loses 2 health, new health 98",
        "Hulk becomes active",
        "Player Schnuzgi loses 2 health, new health 96",
        "Hulk becomes active",
        "Player Schnuzgi loses 2 health, new health 94",
        "Handdeck size: 4 (Weasel,Lynx,Hamster,Hamster)",
        "Fightdeck size: 1 (Porcupine)",
        "Hamsterdeck size: 8 (Hamster,Hamster,Hamster,Hamster,Hamster,Hamster,Hamster,Hamster)",
        "Useddeck size: 1 (Koala)",
        "Human draws Porcupine",
        "Human plays Weasel on GridPos(line=2, slot=1)",
        "Handdeck size: 4 (Lynx,Hamster,Hamster,Porcupine)",
        "Fightdeck size: 0 ()",
        "Hamsterdeck size: 8 (Hamster,Hamster,Hamster,Hamster,Hamster,Hamster,Hamster,Hamster)",
        "Useddeck size: 2 (Koala,Weasel)",
        "Koala becomes active",
        "Koala attacks Hulk",
        "Hulk gets attacked by Koala",
        "Hulk new health: 98",
        "Weasel becomes active",
        "Weasel attacks Hulk",
        "Hulk gets attacked by Weasel",
        "Hulk new health: 99",
        "Hulk becomes active",
        "Hulk attacks Koala",
        "Koala gets attacked by Hulk",
        "Koala dies.",
        "Removed card from [2, 0]",
        "Hulk becomes active",
        "Hulk attacks Weasel",
        "Weasel gets attacked by Hulk",
        "Weasel dies.",
        "Removed card from [2, 1]",
        "Hulk becomes active",
        "Player Schnuzgi loses 2 health, new health 92",
        "Hulk becomes active",
        "Player Schnuzgi loses 2 health, new health 90",
        "Handdeck size: 4 (Lynx,Hamster,Hamster,Porcupine)",
        "Fightdeck size: 0 ()",
        "Hamsterdeck size: 8 (Hamster,Hamster,Hamster,Hamster,Hamster,Hamster,Hamster,Hamster)",
        "Useddeck size: 2 (Koala,Weasel)",
        "Human draws Hamster",
        "Human plays Lynx on GridPos(line=2, slot=0)",
        "Handdeck size: 4 (Hamster,Hamster,Porcupine,Hamster)",
        "Fightdeck size: 0 ()",
        "Hamsterdeck size: 7 (Hamster,Hamster,Hamster,Hamster,Hamster,Hamster,Hamster)",
        "Useddeck size: 3 (Koala,Weasel,Lynx)",
        "Lynx becomes active",
        "Lynx attacks Hulk",
        "Hulk gets attacked by Lynx",
        "Hulk new health: 95",
        "Hulk becomes active",
        "Hulk attacks Lynx",
        "Lynx gets attacked by Hulk",
        "Lynx dies.",
        "Removed card from [2, 0]",
        "Hulk becomes active",
        "Player Schnuzgi loses 2 health, new health 88",
        "Hulk becomes active",
        "Player Schnuzgi loses 2 health, new health 86",
        "Hulk becomes active",
        "Player Schnuzgi loses 2 health, new health 84",
        "Handdeck size: 4 (Hamster,Hamster,Porcupine,Hamster)",
        "Fightdeck size: 0 ()",
        "Hamsterdeck size: 7 (Hamster,Hamster,Hamster,Hamster,Hamster,Hamster,Hamster)",
        "Useddeck size: 3 (Koala,Weasel,Lynx)",
        "Human draws Hamster",
        "Human plays Hamster on GridPos(line=2, slot=0)",
        "Handdeck size: 4 (Hamster,Porcupine,Hamster,Hamster)",
        "Fightdeck size: 0 ()",
        "Hamsterdeck size: 6 (Hamster,Hamster,Hamster,Hamster,Hamster,Hamster)",
        "Useddeck size: 4 (Koala,Weasel,Lynx,Hamster)",
        "Hamster becomes active",
        "Hamster would attack but has 0 power, so doesn't",
        "Hulk becomes active",
        "Hulk attacks Hamster",
        "Hamster gets attacked by Hulk",
        "Hamster dies.",
        "Removed card from [2, 0]",
        "Hulk becomes active",
        "Player Schnuzgi loses 2 health, new health 82",
        "Hulk becomes active",
        "Player Schnuzgi loses 2 health, new health 80",
        "Hulk becomes active",
        "Player Schnuzgi loses 2 health, new health 78",
        "Handdeck size: 4 (Hamster,Porcupine,Hamster,Hamster)",
        "Fightdeck size: 0 ()",
        "Hamsterdeck size: 6 (Hamster,Hamster,Hamster,Hamster,Hamster,Hamster)",
        "Useddeck size: 4 (Koala,Weasel,Lynx,Hamster)",
        "Human draws Hamster",
        "Human plays Hamster on GridPos(line=2, slot=0)",
        "Handdeck size: 4 (Porcupine,Hamster,Hamster,Hamster)",
        "Fightdeck size: 0 ()",
        "Hamsterdeck size: 5 (Hamster,Hamster,Hamster,Hamster,Hamster)",
        "Useddeck size: 5 (Koala,Weasel,Lynx,Hamster,Hamster)",
        "Hamster becomes active",
        "Hamster would attack but has 0 power, so doesn't",
        "Hulk becomes active",
        "Hulk attacks Hamster",
        "Hamster gets attacked by Hulk",
        "Hamster dies.",
        "Removed card from [2, 0]",
        "Hulk becomes active",
        "Player Schnuzgi loses 2 health, new health 76",
        "Hulk becomes active",
        "Player Schnuzgi loses 2 health, new health 74",
        "Hulk becomes active",
        "Player Schnuzgi loses 2 health, new health 72",
        "Handdeck size: 4 (Porcupine,Hamster,Hamster,Hamster)",
        "Fightdeck size: 0 ()",
        "Hamsterdeck size: 5 (Hamster,Hamster,Hamster,Hamster,Hamster)",
        "Useddeck size: 5 (Koala,Weasel,Lynx,Hamster,Hamster)",
        "Human draws Hamster",
        "Human plays Porcupine on GridPos(line=2, slot=0)",
        "Handdeck size: 4 (Hamster,Hamster,Hamster,Hamster)",
        "Fightdeck size: 0 ()",
        "Hamsterdeck size: 4 (Hamster,Hamster,Hamster,Hamster)",
        "Useddeck size: 6 (Koala,Weasel,Lynx,Hamster,Hamster,Porcupine)",
        "Porcupine becomes active",
        "Porcupine🚀 attacks Hulk",
        "Hulk gets attacked by Porcupine",
        "Hulk new health: 94",
        "Hulk becomes active",
        "Hulk attacks Porcupine 🚀",
        "Porcupine gets attacked by Hulk",
        "Porcupine dies.",
        "Removed card from [2, 0]",
        "Hulk becomes active",
        "Player Schnuzgi loses 2 health, new health 70",
        "Hulk becomes active",
        "Player Schnuzgi loses 2 health, new health 68",
        "Hulk becomes active",
        "Player Schnuzgi loses 2 health, new health 66",
        "Handdeck size: 4 (Hamster,Hamster,Hamster,Hamster)",
        "Fightdeck size: 0 ()",
        "Hamsterdeck size: 4 (Hamster,Hamster,Hamster,Hamster)",
        "Useddeck size: 6 (Koala,Weasel,Lynx,Hamster,Hamster,Porcupine)",
        "Human draws Hamster",
        "Human plays Hamster on GridPos(line=2, slot=0)",
        "Handdeck size: 4 (Hamster,Hamster,Hamster,Hamster)",
        "Fightdeck size: 0 ()",
        "Hamsterdeck size: 3 (Hamster,Hamster,Hamster)",
        "Useddeck size: 7 (Koala,Weasel,Lynx,Hamster,Hamster,Porcupine,Hamster)",
        "Hamster becomes active",
        "Hamster would attack but has 0 power, so doesn't",
        "Hulk becomes active",
        "Hulk attacks Hamster",
        "Hamster gets attacked by Hulk",
        "Hamster dies.",
        "Removed card from [2, 0]",
        "Hulk becomes active",
        "Player Schnuzgi loses 2 health, new health 64",
        "Hulk becomes active",
        "Player Schnuzgi loses 2 health, new health 62",
        "Hulk becomes active",
        "Player Schnuzgi loses 2 health, new health 60",
        "Handdeck size: 4 (Hamster,Hamster,Hamster,Hamster)",
        "Fightdeck size: 0 ()",
        "Hamsterdeck size: 3 (Hamster,Hamster,Hamster)",
        "Useddeck size: 7 (Koala,Weasel,Lynx,Hamster,Hamster,Porcupine,Hamster)",
        "Human draws Hamster",
        "Human plays Hamster on GridPos(line=2, slot=0)",
        "Handdeck size: 4 (Hamster,Hamster,Hamster,Hamster)",
        "Fightdeck size: 0 ()",
        "Hamsterdeck size: 2 (Hamster,Hamster)",
        "Useddeck size: 8 (Koala,Weasel,Lynx,Hamster,Hamster,Porcupine,Hamster,Hamster)",
        "Hamster becomes active",
        "Hamster would attack but has 0 power, so doesn't",
        "Hulk becomes active",
        "Hulk attacks Hamster",
        "Hamster gets attacked by Hulk",
        "Hamster dies.",
        "Removed card from [2, 0]",
        "Hulk becomes active",
        "Player Schnuzgi loses 2 health, new health 58",
        "Hulk becomes active",
        "Player Schnuzgi loses 2 health, new health 56",
        "Hulk becomes active",
        "Player Schnuzgi loses 2 health, new health 54",
        "Handdeck size: 4 (Hamster,Hamster,Hamster,Hamster)",
        "Fightdeck size: 0 ()",
        "Hamsterdeck size: 2 (Hamster,Hamster)",
        "Useddeck size: 8 (Koala,Weasel,Lynx,Hamster,Hamster,Porcupine,Hamster,Hamster)",
        "Human draws Hamster",
        "Human plays Hamster on GridPos(line=2, slot=0)",
        "Handdeck size: 4 (Hamster,Hamster,Hamster,Hamster)",
        "Fightdeck size: 0 ()",
        "Hamsterdeck size: 1 (Hamster)",
        "Useddeck size: 9 (Koala,Weasel,Lynx,Hamster,Hamster,Porcupine,Hamster,Hamster,Hamster)",
        "Hamster becomes active",
        "Hamster would attack but has 0 power, so doesn't",
        "Hulk becomes active",
        "Hulk attacks Hamster",
        "Hamster gets attacked by Hulk",
        "Hamster dies.",
        "Removed card from [2, 0]",
        "Hulk becomes active",
        "Player Schnuzgi loses 2 health, new health 52",
        "Hulk becomes active",
        "Player Schnuzgi loses 2 health, new health 50",
        "Hulk becomes active",
        "Player Schnuzgi loses 2 health, new health 48",
        "Handdeck size: 4 (Hamster,Hamster,Hamster,Hamster)",
        "Fightdeck size: 0 ()",
        "Hamsterdeck size: 1 (Hamster)",
        "Useddeck size: 9 (Koala,Weasel,Lynx,Hamster,Hamster,Porcupine,Hamster,Hamster,Hamster)",
        "Human draws Hamster",
        "Human plays Hamster on GridPos(line=2, slot=0)",
        "Handdeck size: 4 (Hamster,Hamster,Hamster,Hamster)",
        "Fightdeck size: 0 ()",
        "Hamsterdeck size: 0 ()",
        "Useddeck size: 10 (Koala,Weasel,Lynx,Hamster,Hamster,Porcupine,Hamster,Hamster,Hamster,Hamster)",
        "Hamster becomes active",
        "Hamster would attack but has 0 power, so doesn't",
        "Hulk becomes active",
        "Hulk attacks Hamster",
        "Hamster gets attacked by Hulk",
        "Hamster dies.",
        "Removed card from [2, 0]",
        "Hulk becomes active",
        "Player Schnuzgi loses 2 health, new health 46",
        "Hulk becomes active",
        "Player Schnuzgi loses 2 health, new health 44",
        "Hulk becomes active",
        "Player Schnuzgi loses 2 health, new health 42",
        "Handdeck size: 4 (Hamster,Hamster,Hamster,Hamster)",
        "Fightdeck size: 0 ()",
        "Hamsterdeck size: 0 ()",
        "Useddeck size: 10 (Koala,Weasel,Lynx,Hamster,Hamster,Porcupine,Hamster,Hamster,Hamster,Hamster)",
        "Human plays Hamster on GridPos(line=2, slot=0)",
        "Handdeck size: 3 (Hamster,Hamster,Hamster)",
        "Fightdeck size: 0 ()",
        "Hamsterdeck size: 0 ()",
        "Useddeck size: 11 (Koala,Weasel,Lynx,Hamster,Hamster,Porcupine,Hamster,Hamster,Hamster,Hamster,Hamster)",
        "Hamster becomes active",
        "Hamster would attack but has 0 power, so doesn't",
        "Hulk becomes active",
        "Hulk attacks Hamster",
        "Hamster gets attacked by Hulk",
        "Hamster dies.",
        "Removed card from [2, 0]",
        "Hulk becomes active",
        "Player Schnuzgi loses 2 health, new health 40",
        "Hulk becomes active",
        "Player Schnuzgi loses 2 health, new health 38",
        "Hulk becomes active",
        "Player Schnuzgi loses 2 health, new health 36",
        "Handdeck size: 3 (Hamster,Hamster,Hamster)",
        "Fightdeck size: 0 ()",
        "Hamsterdeck size: 0 ()",
        "Useddeck size: 11 (Koala,Weasel,Lynx,Hamster,Hamster,Porcupine,Hamster,Hamster,Hamster,Hamster,Hamster)",
        "Human plays Hamster on GridPos(line=2, slot=0)",
        "Handdeck size: 2 (Hamster,Hamster)",
        "Fightdeck size: 0 ()",
        "Hamsterdeck size: 0 ()",
        "Useddeck size: 12 (Koala,Weasel,Lynx,Hamster,Hamster,Porcupine,Hamster,Hamster,Hamster,Hamster,Hamster,Hamster)",
        "Hamster becomes active",
        "Hamster would attack but has 0 power, so doesn't",
        "Hulk becomes active",
        "Hulk attacks Hamster",
        "Hamster gets attacked by Hulk",
        "Hamster dies.",
        "Removed card from [2, 0]",
        "Hulk becomes active",
        "Player Schnuzgi loses 2 health, new health 34",
        "Hulk becomes active",
        "Player Schnuzgi loses 2 health, new health 32",
        "Hulk becomes active",
        "Player Schnuzgi loses 2 health, new health 30",
        "Handdeck size: 2 (Hamster,Hamster)",
        "Fightdeck size: 0 ()",
        "Hamsterdeck size: 0 ()",
        "Useddeck size: 12 (Koala,Weasel,Lynx,Hamster,Hamster,Porcupine,Hamster,Hamster,Hamster,Hamster,Hamster,Hamster)",
        "Human plays Hamster on GridPos(line=2, slot=0)",
        "Handdeck size: 1 (Hamster)",
        "Fightdeck size: 0 ()",
        "Hamsterdeck size: 0 ()",
        "Useddeck size: 13 (Koala,Weasel,Lynx,Hamster,Hamster,Porcupine,Hamster,Hamster,Hamster,Hamster,Hamster,Hamster,Hamster)",
        "Hamster becomes active",
        "Hamster would attack but has 0 power, so doesn't",
        "Hulk becomes active",
        "Hulk attacks Hamster",
        "Hamster gets attacked by Hulk",
        "Hamster dies.",
        "Removed card from [2, 0]",
        "Hulk becomes active",
        "Player Schnuzgi loses 2 health, new health 28",
        "Hulk becomes active",
        "Player Schnuzgi loses 2 health, new health 26",
        "Hulk becomes active",
        "Player Schnuzgi loses 2 health, new health 24",
        "Handdeck size: 1 (Hamster)",
        "Fightdeck size: 0 ()",
        "Hamsterdeck size: 0 ()",
        "Useddeck size: 13 (Koala,Weasel,Lynx,Hamster,Hamster,Porcupine,Hamster,Hamster,Hamster,Hamster,Hamster,Hamster,Hamster)",
        "Human plays Hamster on GridPos(line=2, slot=0)",
        "Handdeck size: 0 ()",
        "Fightdeck size: 0 ()",
        "Hamsterdeck size: 0 ()",
        "Useddeck size: 14 (Koala,Weasel,Lynx,Hamster,Hamster,Porcupine,Hamster,Hamster,Hamster,Hamster,Hamster,Hamster,Hamster,Hamster)",
        "Hamster becomes active",
        "Hamster would attack but has 0 power, so doesn't",
        "Hulk becomes active",
        "Hulk attacks Hamster",
        "Hamster gets attacked by Hulk",
        "Hamster dies.",
        "Removed card from [2, 0]",
        "Hulk becomes active",
        "Player Schnuzgi loses 2 health, new health 22",
        "Hulk becomes active",
        "Player Schnuzgi loses 2 health, new health 20",
        "Hulk becomes active",
        "Player Schnuzgi loses 2 health, new health 18",
        "Handdeck size: 0 ()",
        "Fightdeck size: 0 ()",
        "Hamsterdeck size: 0 ()",
        "Useddeck size: 14 (Koala,Weasel,Lynx,Hamster,Hamster,Porcupine,Hamster,Hamster,Hamster,Hamster,Hamster,Hamster,Hamster,Hamster)",
        "Human plays no card.",
        "Handdeck size: 0 ()",
        "Fightdeck size: 0 ()",
        "Hamsterdeck size: 0 ()",
        "Useddeck size: 14 (Koala,Weasel,Lynx,Hamster,Hamster,Porcupine,Hamster,Hamster,Hamster,Hamster,Hamster,Hamster,Hamster,Hamster)",
        "Hulk becomes active",
        "Player Schnuzgi loses 2 health, new health 16",
        "Hulk becomes active",
        "Player Schnuzgi loses 2 health, new health 14",
        "Hulk becomes active",
        "Player Schnuzgi loses 2 health, new health 12",
        "Hulk becomes active",
        "Player Schnuzgi loses 2 health, new health 10",
        "Handdeck size: 0 ()",
        "Fightdeck size: 0 ()",
        "Hamsterdeck size: 0 ()",
        "Useddeck size: 14 (Koala,Weasel,Lynx,Hamster,Hamster,Porcupine,Hamster,Hamster,Hamster,Hamster,Hamster,Hamster,Hamster,Hamster)",
        "Human plays no card.",
        "Handdeck size: 0 ()",
        "Fightdeck size: 0 ()",
        "Hamsterdeck size: 0 ()",
        "Useddeck size: 14 (Koala,Weasel,Lynx,Hamster,Hamster,Porcupine,Hamster,Hamster,Hamster,Hamster,Hamster,Hamster,Hamster,Hamster)",
        "Hulk becomes active",
        "Player Schnuzgi loses 2 health, new health 8",
        "Hulk becomes active",
        "Player Schnuzgi loses 2 health, new health 6",
        "Hulk becomes active",
        "Player Schnuzgi loses 2 health, new health 4",
        "Hulk becomes active",
        "Player Schnuzgi loses 2 health, new health 2",
        "Handdeck size: 0 ()",
        "Fightdeck size: 0 ()",
        "Hamsterdeck size: 0 ()",
        "Useddeck size: 14 (Koala,Weasel,Lynx,Hamster,Hamster,Porcupine,Hamster,Hamster,Hamster,Hamster,Hamster,Hamster,Hamster,Hamster)",
        "Human plays no card.",
        "Handdeck size: 0 ()",
        "Fightdeck size: 0 ()",
        "Hamsterdeck size: 0 ()",
        "Useddeck size: 14 (Koala,Weasel,Lynx,Hamster,Hamster,Porcupine,Hamster,Hamster,Hamster,Hamster,Hamster,Hamster,Hamster,Hamster)",
        "Hulk becomes active",
        "Player Schnuzgi loses 2 health, new health 0",
        "Hulk becomes active",
        "Player Schnuzgi loses 2 health, new health -2",
        "Hulk becomes active",
        "Player Schnuzgi loses 2 health, new health -4",
        "Hulk becomes active",
        "Player Schnuzgi loses 2 health, new health -6",
        "Player Schnuzgi loses 1 life, 0 life/lives left, 6 overflow damage",
    ]:
        assert logentry in caplog.text
